/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    works: Work;
    characters: Character;
    'character-aliases': CharacterAlias;
    manufacturers: Manufacturer;
    'figure-prototypes': FigurePrototype;
    'figure-prototype-characters': FigurePrototypeCharacter;
    'figure-versions': FigureVersion;
    'catalog-items': CatalogItem;
    'source-records': SourceRecord;
    'operation-logs': OperationLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    'character-aliases': CharacterAliasesSelect<false> | CharacterAliasesSelect<true>;
    manufacturers: ManufacturersSelect<false> | ManufacturersSelect<true>;
    'figure-prototypes': FigurePrototypesSelect<false> | FigurePrototypesSelect<true>;
    'figure-prototype-characters': FigurePrototypeCharactersSelect<false> | FigurePrototypeCharactersSelect<true>;
    'figure-versions': FigureVersionsSelect<false> | FigureVersionsSelect<true>;
    'catalog-items': CatalogItemsSelect<false> | CatalogItemsSelect<true>;
    'source-records': SourceRecordsSelect<false> | SourceRecordsSelect<true>;
    'operation-logs': OperationLogsSelect<false> | OperationLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Private infrastructure media used only to validate the storage boundary.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  stableId: string;
  displayName: string;
  originalName?: string | null;
  normalizedName: string;
  workType: 'animation' | 'game' | 'comic' | 'novel' | 'other';
  publicationStatus: 'draft' | 'published' | 'hidden';
  lockVersion: number;
  createdBy: number | User;
  updatedBy: number | User;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  deleteReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  stableId: string;
  work?: (number | null) | Work;
  displayName: string;
  nameZh?: string | null;
  nameJa?: string | null;
  nameEn?: string | null;
  normalizedName: string;
  searchDocument: string;
  status: 'active' | 'matching_pending' | 'hidden';
  lockVersion: number;
  createdBy: number | User;
  updatedBy: number | User;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  deleteReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "character-aliases".
 */
export interface CharacterAlias {
  id: number;
  stableId: string;
  character: number | Character;
  value: string;
  normalizedValue: string;
  locale?: string | null;
  aliasType: 'official' | 'translation' | 'common' | 'romanization' | 'source_only';
  isPreferred: boolean;
  createdBy: number | User;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  deleteReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers".
 */
export interface Manufacturer {
  id: number;
  stableId: string;
  canonicalName: string;
  normalizedName: string;
  aliases?:
    | {
        value: string;
        normalizedValue: string;
        locale?: string | null;
        id?: string | null;
      }[]
    | null;
  officialSiteUrl?: string | null;
  authorizationNote?: string | null;
  sourceEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'draft' | 'active' | 'hidden';
  lockVersion: number;
  createdBy: number | User;
  updatedBy: number | User;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  deleteReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "figure-prototypes".
 */
export interface FigurePrototype {
  id: number;
  stableId: string;
  projectionKey?: string | null;
  membershipFingerprint?: string | null;
  title: string;
  normalizedTitle: string;
  work?: (number | null) | Work;
  manufacturer?: (number | null) | Manufacturer;
  figureType: 'scale' | 'prize' | 'static';
  scale?: string | null;
  costumeText?: string | null;
  isGroup: boolean;
  adultEntryFlag: boolean;
  authorizationStatus: 'pending' | 'official' | 'authorized_third_party' | 'rejected';
  authorizationEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  authorizationReason?: string | null;
  authorizationReviewedBy?: (number | null) | User;
  authorizationReviewedAt?: string | null;
  inclusionStatus: 'pending' | 'eligible' | 'excluded';
  inclusionReason?: string | null;
  inclusionReviewedBy?: (number | null) | User;
  inclusionReviewedAt?: string | null;
  publicationStatus: 'draft' | 'published' | 'hidden' | 'merged' | 'archived';
  mergedInto?: (number | null) | FigurePrototype;
  lockVersion: number;
  createdBy: number | User;
  updatedBy: number | User;
  archivedAt?: string | null;
  archivedBy?: (number | null) | User;
  archiveReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "figure-prototype-characters".
 */
export interface FigurePrototypeCharacter {
  id: number;
  stableId: string;
  prototype: number | FigurePrototype;
  character: number | Character;
  displayOrder: number;
  role: 'primary' | 'secondary' | 'companion';
  createdBy: number | User;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  deleteReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "figure-versions".
 */
export interface FigureVersion {
  id: number;
  stableId: string;
  prototype: number | FigurePrototype;
  name: string;
  normalizedVersionKey: string;
  kind: 'regular' | 'deluxe' | 'reissue' | 'bonus' | 'recolor' | 'channel-exclusive';
  channelOrDistributorLabel?: string | null;
  releaseStatus:
    'announced' | 'gray_prototype' | 'painted_prototype' | 'preorder' | 'released' | 'cancelled' | 'unknown';
  grayModelCompleteness: 'not_applicable' | 'complete' | 'partial' | 'unknown';
  releaseDate?: string | null;
  skuOrCode?: string | null;
  notes?: string | null;
  lockVersion: number;
  createdBy: number | User;
  updatedBy: number | User;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  deleteReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-items".
 */
export interface CatalogItem {
  id: number;
  stableId: string;
  catalogItemKey: string;
  character: number | Character;
  prototype: number | FigurePrototype;
  title: string;
  manufacturerText: string;
  classification: string;
  category?: string | null;
  scale?: string | null;
  heightMm?: number | null;
  release?: string | null;
  productType?: string | null;
  series?: string | null;
  description?: string | null;
  imageRefs?:
    | {
        imageRefKey: string;
        url: string;
        sourceFamily: string;
        catalogItemKey: string;
        isMain: boolean;
        id?: string | null;
      }[]
    | null;
  lockVersion: number;
  createdBy: number | User;
  updatedBy: number | User;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  deleteReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-records".
 */
export interface SourceRecord {
  id: number;
  stableId: string;
  sourceRecordKey: string;
  sourceFamily: string;
  sourceUrl: string;
  observedTitle?: string | null;
  observedManufacturer?: string | null;
  sourceLabel?: string | null;
  sourceRole?: string | null;
  character: number | Character;
  catalogItem: number | CatalogItem;
  businessDigest: string;
  businessDigestVersion: number;
  lockVersion: number;
  createdBy: number | User;
  updatedBy: number | User;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  deleteReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operation-logs".
 */
export interface OperationLog {
  id: number;
  operationId: string;
  actorUser?: (number | null) | User;
  actorType: 'admin' | 'system';
  dutyContext: 'catalog_maintenance' | 'catalog_review';
  action: string;
  scopeType: string;
  scopeStableId: string;
  reason: string;
  expectedVersion?: number | null;
  resultVersion: number;
  beforeSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  afterSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestDigest: string;
  reversible: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'character-aliases';
        value: number | CharacterAlias;
      } | null)
    | ({
        relationTo: 'manufacturers';
        value: number | Manufacturer;
      } | null)
    | ({
        relationTo: 'figure-prototypes';
        value: number | FigurePrototype;
      } | null)
    | ({
        relationTo: 'figure-prototype-characters';
        value: number | FigurePrototypeCharacter;
      } | null)
    | ({
        relationTo: 'figure-versions';
        value: number | FigureVersion;
      } | null)
    | ({
        relationTo: 'catalog-items';
        value: number | CatalogItem;
      } | null)
    | ({
        relationTo: 'source-records';
        value: number | SourceRecord;
      } | null)
    | ({
        relationTo: 'operation-logs';
        value: number | OperationLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  stableId?: T;
  displayName?: T;
  originalName?: T;
  normalizedName?: T;
  workType?: T;
  publicationStatus?: T;
  lockVersion?: T;
  createdBy?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  deleteReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  stableId?: T;
  work?: T;
  displayName?: T;
  nameZh?: T;
  nameJa?: T;
  nameEn?: T;
  normalizedName?: T;
  searchDocument?: T;
  status?: T;
  lockVersion?: T;
  createdBy?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  deleteReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "character-aliases_select".
 */
export interface CharacterAliasesSelect<T extends boolean = true> {
  stableId?: T;
  character?: T;
  value?: T;
  normalizedValue?: T;
  locale?: T;
  aliasType?: T;
  isPreferred?: T;
  createdBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  deleteReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers_select".
 */
export interface ManufacturersSelect<T extends boolean = true> {
  stableId?: T;
  canonicalName?: T;
  normalizedName?: T;
  aliases?:
    | T
    | {
        value?: T;
        normalizedValue?: T;
        locale?: T;
        id?: T;
      };
  officialSiteUrl?: T;
  authorizationNote?: T;
  sourceEvidence?: T;
  status?: T;
  lockVersion?: T;
  createdBy?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  deleteReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "figure-prototypes_select".
 */
export interface FigurePrototypesSelect<T extends boolean = true> {
  stableId?: T;
  projectionKey?: T;
  membershipFingerprint?: T;
  title?: T;
  normalizedTitle?: T;
  work?: T;
  manufacturer?: T;
  figureType?: T;
  scale?: T;
  costumeText?: T;
  isGroup?: T;
  adultEntryFlag?: T;
  authorizationStatus?: T;
  authorizationEvidence?: T;
  authorizationReason?: T;
  authorizationReviewedBy?: T;
  authorizationReviewedAt?: T;
  inclusionStatus?: T;
  inclusionReason?: T;
  inclusionReviewedBy?: T;
  inclusionReviewedAt?: T;
  publicationStatus?: T;
  mergedInto?: T;
  lockVersion?: T;
  createdBy?: T;
  updatedBy?: T;
  archivedAt?: T;
  archivedBy?: T;
  archiveReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "figure-prototype-characters_select".
 */
export interface FigurePrototypeCharactersSelect<T extends boolean = true> {
  stableId?: T;
  prototype?: T;
  character?: T;
  displayOrder?: T;
  role?: T;
  createdBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  deleteReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "figure-versions_select".
 */
export interface FigureVersionsSelect<T extends boolean = true> {
  stableId?: T;
  prototype?: T;
  name?: T;
  normalizedVersionKey?: T;
  kind?: T;
  channelOrDistributorLabel?: T;
  releaseStatus?: T;
  grayModelCompleteness?: T;
  releaseDate?: T;
  skuOrCode?: T;
  notes?: T;
  lockVersion?: T;
  createdBy?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  deleteReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-items_select".
 */
export interface CatalogItemsSelect<T extends boolean = true> {
  stableId?: T;
  catalogItemKey?: T;
  character?: T;
  prototype?: T;
  title?: T;
  manufacturerText?: T;
  classification?: T;
  category?: T;
  scale?: T;
  heightMm?: T;
  release?: T;
  productType?: T;
  series?: T;
  description?: T;
  imageRefs?:
    | T
    | {
        imageRefKey?: T;
        url?: T;
        sourceFamily?: T;
        catalogItemKey?: T;
        isMain?: T;
        id?: T;
      };
  lockVersion?: T;
  createdBy?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  deleteReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-records_select".
 */
export interface SourceRecordsSelect<T extends boolean = true> {
  stableId?: T;
  sourceRecordKey?: T;
  sourceFamily?: T;
  sourceUrl?: T;
  observedTitle?: T;
  observedManufacturer?: T;
  sourceLabel?: T;
  sourceRole?: T;
  character?: T;
  catalogItem?: T;
  businessDigest?: T;
  businessDigestVersion?: T;
  lockVersion?: T;
  createdBy?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  deleteReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operation-logs_select".
 */
export interface OperationLogsSelect<T extends boolean = true> {
  operationId?: T;
  actorUser?: T;
  actorType?: T;
  dutyContext?: T;
  action?: T;
  scopeType?: T;
  scopeStableId?: T;
  reason?: T;
  expectedVersion?: T;
  resultVersion?: T;
  beforeSnapshot?: T;
  afterSnapshot?: T;
  requestDigest?: T;
  reversible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}