import {
  FIGURE_TYPES,
  PROTOTYPE_AUTHORIZATION_STATUSES,
  PROTOTYPE_INCLUSION_STATUSES,
  PROTOTYPE_PUBLICATION_STATUSES,
} from '@figure-gallery/domain-contracts'
import type { CollectionConfig } from 'payload'

import {
  actorField,
  archiveFields,
  attributionFields,
  catalogCollection,
  catalogRelationTo,
  immutableTextField,
  lockVersionField,
  selectOptions,
  sha256HexField,
  stableIdField,
} from './common'

export const FigurePrototype: CollectionConfig = catalogCollection({
  slug: 'figure-prototypes',
  dbName: 'figure_prototypes',
  admin: {
    defaultColumns: [
      'title',
      'manufacturer',
      'figureType',
      'authorizationStatus',
      'inclusionStatus',
      'publicationStatus',
    ],
    group: 'Catalog',
    useAsTitle: 'title',
  },
  fields: [
    stableIdField(),
    immutableTextField('projectionKey', { maxLength: 255, required: false }),
    sha256HexField('membershipFingerprint', false),
    {
      name: 'title',
      type: 'text',
      admin: { readOnly: true },
      required: true,
    },
    {
      name: 'normalizedTitle',
      type: 'text',
      admin: { readOnly: true },
      index: true,
      required: true,
    },
    {
      name: 'work',
      type: 'relationship',
      admin: { readOnly: true },
      index: true,
      relationTo: catalogRelationTo('works'),
    },
    {
      name: 'manufacturer',
      type: 'relationship',
      admin: { readOnly: true },
      index: true,
      relationTo: catalogRelationTo('manufacturers'),
    },
    {
      name: 'figureType',
      type: 'select',
      admin: { readOnly: true },
      enumName: 'enum_figure_prototypes_figure_type',
      options: selectOptions(FIGURE_TYPES),
      required: true,
    },
    {
      name: 'scale',
      type: 'text',
      admin: { readOnly: true },
    },
    {
      name: 'costumeText',
      type: 'text',
      admin: { readOnly: true },
    },
    {
      name: 'isGroup',
      type: 'checkbox',
      admin: { readOnly: true },
      defaultValue: false,
      required: true,
    },
    {
      name: 'adultEntryFlag',
      type: 'checkbox',
      admin: { readOnly: true },
      defaultValue: false,
      required: true,
      validate: (value) => value === false || 'adultEntryFlag must remain false until PR-04.',
    },
    {
      name: 'authorizationStatus',
      type: 'select',
      admin: { readOnly: true },
      defaultValue: 'pending',
      enumName: 'enum_figure_prototypes_authorization_status',
      options: selectOptions(PROTOTYPE_AUTHORIZATION_STATUSES),
      required: true,
    },
    {
      name: 'authorizationEvidence',
      type: 'json',
      admin: { readOnly: true },
    },
    {
      name: 'authorizationReason',
      type: 'textarea',
      admin: { readOnly: true },
    },
    actorField('authorizationReviewedBy', false),
    {
      name: 'authorizationReviewedAt',
      type: 'date',
      admin: { readOnly: true },
    },
    {
      name: 'inclusionStatus',
      type: 'select',
      admin: { readOnly: true },
      defaultValue: 'pending',
      enumName: 'enum_figure_prototypes_inclusion_status',
      options: selectOptions(PROTOTYPE_INCLUSION_STATUSES),
      required: true,
    },
    {
      name: 'inclusionReason',
      type: 'textarea',
      admin: { readOnly: true },
    },
    actorField('inclusionReviewedBy', false),
    {
      name: 'inclusionReviewedAt',
      type: 'date',
      admin: { readOnly: true },
    },
    {
      name: 'publicationStatus',
      type: 'select',
      admin: { readOnly: true },
      defaultValue: 'draft',
      enumName: 'enum_figure_prototypes_publication_status',
      options: selectOptions(PROTOTYPE_PUBLICATION_STATUSES),
      required: true,
    },
    {
      name: 'mergedInto',
      type: 'relationship',
      admin: { readOnly: true },
      index: true,
      relationTo: catalogRelationTo('figure-prototypes'),
    },
    lockVersionField(),
    ...attributionFields(),
    ...archiveFields(),
  ],
})
