/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    works: Work;
    characters: Character;
    manufacturers: Manufacturer;
    media: Media;
    'figure-prototypes': FigurePrototype;
    'figure-versions': FigureVersion;
    'source-records': SourceRecord;
    'candidate-records': CandidateRecord;
    'review-work-items': ReviewWorkItem;
    'operation-logs': OperationLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    manufacturers: ManufacturersSelect<false> | ManufacturersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'figure-prototypes': FigurePrototypesSelect<false> | FigurePrototypesSelect<true>;
    'figure-versions': FigureVersionsSelect<false> | FigureVersionsSelect<true>;
    'source-records': SourceRecordsSelect<false> | SourceRecordsSelect<true>;
    'candidate-records': CandidateRecordsSelect<false> | CandidateRecordsSelect<true>;
    'review-work-items': ReviewWorkItemsSelect<false> | ReviewWorkItemsSelect<true>;
    'operation-logs': OperationLogsSelect<false> | OperationLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'system-settings': SystemSetting;
  };
  globalsSelect: {
    'system-settings': SystemSettingsSelect<false> | SystemSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'candidate-client';
  /**
   * Stable runtime-provisioned client identity; not a credential.
   */
  candidateClientID?: string | null;
  candidateActive: boolean;
  candidateTokenHash?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  fixtureID?: string | null;
  name: string;
  originalName?: string | null;
  aliases?: string[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  fixtureID?: string | null;
  displayName: string;
  nameZh?: string | null;
  nameJa?: string | null;
  nameEn?: string | null;
  aliases?: string[] | null;
  work?: (number | null) | Work;
  status: 'active' | 'hidden' | 'matching-pending';
  softDeleted: boolean;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers".
 */
export interface Manufacturer {
  id: number;
  fixtureID?: string | null;
  canonicalName: string;
  aliases?: string[] | null;
  status: 'draft' | 'active' | 'hidden';
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  fixtureID?: string | null;
  candidateOnly: boolean;
  candidate?: (number | null) | CandidateRecord;
  candidateOwner?: (number | null) | User;
  clientCandidateID?: string | null;
  idempotencyKey?: string | null;
  prototype?: (number | null) | FigurePrototype;
  sourceUrl: string;
  storageKey: string;
  byteSize?: number | null;
  pixelWidth?: number | null;
  pixelHeight?: number | null;
  format?: string | null;
  sha256: string;
  perceptualHash?: string | null;
  isAdult: boolean;
  isSourceHomepage: boolean;
  presentInLatestSource: boolean;
  selectedAsMain: boolean;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    preview?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-records".
 */
export interface CandidateRecord {
  id: number;
  externalKey: string;
  candidateOwner?: (number | null) | User;
  source: number | SourceRecord;
  rawTitle: string;
  rawCharacterNames?: string[] | null;
  rawWorkName?: string | null;
  rawManufacturer?: string | null;
  rawCategory?: string | null;
  rawScale?: string | null;
  rawDate?: string | null;
  rawSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'accepted' | 'deferred' | 'ignored' | 'merged' | 'update_pending';
  reason?: string | null;
  matchState: 'character_pending' | 'manufacturer_pending' | 'matched';
  proposedManufacturerStatus?: ('draft' | 'active' | 'hidden') | null;
  requestedChanges?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  acceptedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rejectedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  targetPrototype?: (number | null) | FigurePrototype;
  targetVersion?: (number | null) | FigureVersion;
  images?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-records".
 */
export interface SourceRecord {
  id: number;
  fixtureID?: string | null;
  candidateOnly: boolean;
  candidateOwner?: (number | null) | User;
  sourceType: string;
  sourceItemId?: string | null;
  sourceUrl: string;
  canonicalUrl: string;
  sourceKey: string;
  status: 'active' | 'missing' | 'blocked';
  lastSyncedAt?: string | null;
  invalidated: boolean;
  rawSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  prototype?: (number | null) | FigurePrototype;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "figure-prototypes".
 */
export interface FigurePrototype {
  id: number;
  fixtureID?: string | null;
  title: string;
  characters: (number | Character)[];
  work?: (number | null) | Work;
  manufacturer: number | Manufacturer;
  figureType: 'scale' | 'prize';
  scale?: string | null;
  costumeText?: string | null;
  isGroup: boolean;
  isAdult: boolean;
  publicationStatus: 'draft' | 'published' | 'hidden' | 'merged';
  softDeleted: boolean;
  lockVersion: number;
  /**
   * Read-only here; use Candidate review workbench so the change is audited.
   */
  mainImage?: (number | null) | Media;
  mergedInto?: (number | null) | FigurePrototype;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "figure-versions".
 */
export interface FigureVersion {
  id: number;
  fixtureID?: string | null;
  prototype: number | FigurePrototype;
  name: string;
  kind: 'standard' | 'deluxe' | 'reissue' | 'bonus' | 'recolor' | 'channel-limited';
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-work-items".
 */
export interface ReviewWorkItem {
  id: number;
  candidate: number | CandidateRecord;
  allowedTargets?: (number | FigurePrototype)[] | null;
  reviewer: number | User;
  status: 'open' | 'completed' | 'cancelled';
  lockVersion: number;
  startedAt: string;
  completedAt?: string | null;
  decisionReason?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operation-logs".
 */
export interface OperationLog {
  id: number;
  fixtureID?: string | null;
  operationID?: string | null;
  operationVersion: number;
  scope?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dependsOn?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  actor?: (number | null) | User;
  actorLabel: string;
  operationType:
    | 'candidate_upsert'
    | 'candidate_media_upload'
    | 'client_revoked'
    | 'create_manufacturer'
    | 'create_prototype'
    | 'attach_version'
    | 'accept_field'
    | 'reject_field'
    | 'defer_candidate'
    | 'ignore_candidate'
    | 'set_manufacturer_status'
    | 'set_prototype_publication'
    | 'select_main_image'
    | 'update_settings'
    | 'merge'
    | 'split'
    | 'undo_merge'
    | 'undo_split'
    | 'review_work_item_opened'
    | 'review_work_item_reopened'
    | 'review_work_item_completed'
    | 'maintain_formal';
  reason: string;
  beforeState:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  afterState:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  relatedRecords:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  inversePayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  undone: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'manufacturers';
        value: number | Manufacturer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'figure-prototypes';
        value: number | FigurePrototype;
      } | null)
    | ({
        relationTo: 'figure-versions';
        value: number | FigureVersion;
      } | null)
    | ({
        relationTo: 'source-records';
        value: number | SourceRecord;
      } | null)
    | ({
        relationTo: 'candidate-records';
        value: number | CandidateRecord;
      } | null)
    | ({
        relationTo: 'review-work-items';
        value: number | ReviewWorkItem;
      } | null)
    | ({
        relationTo: 'operation-logs';
        value: number | OperationLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  candidateClientID?: T;
  candidateActive?: T;
  candidateTokenHash?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  fixtureID?: T;
  name?: T;
  originalName?: T;
  aliases?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  fixtureID?: T;
  displayName?: T;
  nameZh?: T;
  nameJa?: T;
  nameEn?: T;
  aliases?: T;
  work?: T;
  status?: T;
  softDeleted?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers_select".
 */
export interface ManufacturersSelect<T extends boolean = true> {
  fixtureID?: T;
  canonicalName?: T;
  aliases?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  fixtureID?: T;
  candidateOnly?: T;
  candidate?: T;
  candidateOwner?: T;
  clientCandidateID?: T;
  idempotencyKey?: T;
  prototype?: T;
  sourceUrl?: T;
  storageKey?: T;
  byteSize?: T;
  pixelWidth?: T;
  pixelHeight?: T;
  format?: T;
  sha256?: T;
  perceptualHash?: T;
  isAdult?: T;
  isSourceHomepage?: T;
  presentInLatestSource?: T;
  selectedAsMain?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        preview?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "figure-prototypes_select".
 */
export interface FigurePrototypesSelect<T extends boolean = true> {
  fixtureID?: T;
  title?: T;
  characters?: T;
  work?: T;
  manufacturer?: T;
  figureType?: T;
  scale?: T;
  costumeText?: T;
  isGroup?: T;
  isAdult?: T;
  publicationStatus?: T;
  softDeleted?: T;
  lockVersion?: T;
  mainImage?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "figure-versions_select".
 */
export interface FigureVersionsSelect<T extends boolean = true> {
  fixtureID?: T;
  prototype?: T;
  name?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-records_select".
 */
export interface SourceRecordsSelect<T extends boolean = true> {
  fixtureID?: T;
  candidateOnly?: T;
  candidateOwner?: T;
  sourceType?: T;
  sourceItemId?: T;
  sourceUrl?: T;
  canonicalUrl?: T;
  sourceKey?: T;
  status?: T;
  lastSyncedAt?: T;
  invalidated?: T;
  rawSnapshot?: T;
  prototype?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-records_select".
 */
export interface CandidateRecordsSelect<T extends boolean = true> {
  externalKey?: T;
  candidateOwner?: T;
  source?: T;
  rawTitle?: T;
  rawCharacterNames?: T;
  rawWorkName?: T;
  rawManufacturer?: T;
  rawCategory?: T;
  rawScale?: T;
  rawDate?: T;
  rawSnapshot?: T;
  status?: T;
  reason?: T;
  matchState?: T;
  proposedManufacturerStatus?: T;
  requestedChanges?: T;
  acceptedFields?: T;
  rejectedFields?: T;
  targetPrototype?: T;
  targetVersion?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-work-items_select".
 */
export interface ReviewWorkItemsSelect<T extends boolean = true> {
  candidate?: T;
  allowedTargets?: T;
  reviewer?: T;
  status?: T;
  lockVersion?: T;
  startedAt?: T;
  completedAt?: T;
  decisionReason?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operation-logs_select".
 */
export interface OperationLogsSelect<T extends boolean = true> {
  fixtureID?: T;
  operationID?: T;
  operationVersion?: T;
  scope?: T;
  dependsOn?: T;
  actor?: T;
  actorLabel?: T;
  operationType?: T;
  reason?: T;
  beforeState?: T;
  afterState?: T;
  relatedRecords?: T;
  inversePayload?: T;
  undone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings".
 */
export interface SystemSetting {
  id: number;
  showAdultImages: boolean;
  galleryPageSize: number;
  publicReadEnabled: boolean;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings_select".
 */
export interface SystemSettingsSelect<T extends boolean = true> {
  showAdultImages?: T;
  galleryPageSize?: T;
  publicReadEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}