# Generated by Django 5.2.16 on 2026-07-13 18:36

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=200)),
                ("name_zh", models.CharField(blank=True, max_length=200)),
                ("name_ja", models.CharField(blank=True, max_length=200)),
                ("name_en", models.CharField(blank=True, max_length=200)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_soft_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("hidden", "Hidden"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, unique=True),
                ),
                ("show_adult_images", models.BooleanField(default=False)),
                ("page_size", models.PositiveSmallIntegerField(default=16)),
                ("public_access_enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("original_name", models.CharField(blank=True, max_length=200)),
                ("aliases", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FigurePrototype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                (
                    "figure_type",
                    models.CharField(
                        choices=[("scale", "Scale figure"), ("prize", "Prize figure")],
                        max_length=16,
                    ),
                ),
                ("scale", models.CharField(blank=True, max_length=40)),
                ("costume_skin_text", models.CharField(blank=True, max_length=240)),
                ("is_multi_character", models.BooleanField(default=False)),
                ("is_adult", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_soft_deleted", models.BooleanField(default=False)),
                ("is_merged", models.BooleanField(default=False)),
                (
                    "characters",
                    modelcluster.fields.ParentalManyToManyField(
                        related_name="figure_prototypes", to="gallery.character"
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "main_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="figure_gallery_main_for",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merged_records",
                        to="gallery.figureprototype",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prototypes",
                        to="gallery.manufacturer",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prototypes",
                        to="gallery.work",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="FigureVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("deluxe", "Deluxe"),
                            ("reissue", "Reissue"),
                            ("bonus", "Bonus"),
                            ("recolor", "Recolor"),
                            ("channel", "Channel exclusive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "prototype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="gallery.figureprototype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_label", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("candidate_upsert", "Candidate upsert"),
                            ("review", "Candidate review"),
                            ("main_image", "Main image selection"),
                            ("merge", "Merge"),
                            ("split", "Split"),
                            ("undo", "Undo"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField()),
                ("before_state", models.JSONField(default=dict)),
                ("after_state", models.JSONField(default=dict)),
                ("related_records", models.JSONField(default=dict)),
                ("is_undone", models.BooleanField(default=False)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="figure_gallery_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "undo_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="undo_record",
                        to="gallery.operationlog",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(max_length=40)),
                ("source_item_id", models.CharField(blank=True, max_length=160)),
                ("source_url", models.URLField(max_length=1000)),
                ("normalized_url", models.URLField(max_length=1000)),
                ("source_status", models.CharField(blank=True, max_length=80)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("is_unavailable", models.BooleanField(default=False)),
                ("raw_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "prototype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="gallery.figureprototype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_title", models.CharField(max_length=500)),
                ("raw_character_names", models.JSONField(blank=True, default=list)),
                ("raw_work_name", models.CharField(blank=True, max_length=240)),
                ("raw_manufacturer", models.CharField(blank=True, max_length=240)),
                ("raw_category", models.CharField(blank=True, max_length=120)),
                ("raw_scale", models.CharField(blank=True, max_length=80)),
                ("raw_release_date", models.CharField(blank=True, max_length=100)),
                ("raw_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("deferred", "Deferred"),
                            ("ignored", "Ignored"),
                            ("merged", "Merged"),
                            ("update_pending", "Update pending"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("review_reason", models.TextField(blank=True)),
                ("field_decisions", models.JSONField(blank=True, default=dict)),
                (
                    "unmatched_character_names",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "unmatched_manufacturer_name",
                    models.CharField(blank=True, max_length=240),
                ),
                (
                    "target_prototype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="gallery.figureprototype",
                    ),
                ),
                (
                    "target_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="gallery.figureversion",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate",
                        to="gallery.sourcerecord",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="character",
            name="work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to="gallery.work",
            ),
        ),
        migrations.CreateModel(
            name="CandidateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_url", models.URLField(blank=True, max_length=1000)),
                ("storage_key", models.CharField(max_length=500)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("format", models.CharField(max_length=20)),
                ("sha256", models.CharField(max_length=64)),
                ("perceptual_hash", models.CharField(blank=True, max_length=64)),
                ("is_adult", models.BooleanField(default=False)),
                ("is_source_homepage", models.BooleanField(default=False)),
                ("exists_in_latest_source", models.BooleanField(default=True)),
                ("selected_as_main", models.BooleanField(default=False)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="figure_gallery_candidates",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="gallery.candidaterecord",
                    ),
                ),
                (
                    "prototype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_images",
                        to="gallery.figureprototype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("candidate__isnull", False),
                            ("prototype__isnull", False),
                            _connector="OR",
                        ),
                        name="gallery_candidate_image_has_owner",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sourcerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_item_id", ""), _negated=True),
                fields=("source_type", "source_item_id"),
                name="gallery_unique_source_stable_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_item_id", "")),
                fields=("source_type", "normalized_url"),
                name="gallery_unique_source_url_fallback",
            ),
        ),
    ]
