# Generated by Django 5.2.16 on 2026-07-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateimage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="figure_gallery_candidates",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("candidate__isnull", False)),
                fields=("candidate", "storage_key"),
                name="gallery_unique_candidate_storage_key",
            ),
        ),
    ]
