# Generated by Django 5.2.16 on 2026-07-14 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_operation_ids(apps, schema_editor):
    operation_log = apps.get_model("gallery", "OperationLog")
    for operation in operation_log.objects.filter(operation_id=None).iterator():
        operation.operation_id = uuid.uuid4()
        operation.save(update_fields=["operation_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_candidateimage_image_and_more"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateClientCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_id", models.CharField(max_length=120, unique=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CandidateUploadReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.CharField(max_length=200)),
                ("sha256", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewWorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("completed", "Completed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("lock_version", models.PositiveBigIntegerField(default=1)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("reopen_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="candidateimage",
            name="client_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="candidateimage",
            name="content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="candidateimage",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidaterecord",
            name="client_candidate_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="figureprototype",
            name="domain_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="operation_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_operation_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="operationlog",
            name="operation_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="scope",
            field=models.CharField(default="gallery", max_length=200),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="scope_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("candidate_upsert", "Candidate upsert"),
                    ("review", "Candidate review"),
                    ("main_image", "Main image selection"),
                    ("client_identity", "Candidate client identity"),
                    ("review_work", "Review work item"),
                    ("merge", "Merge"),
                    ("split", "Split"),
                    ("undo", "Undo"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("candidate", "idempotency_key"),
                name="gallery_unique_candidate_media_idempotency",
            ),
        ),
        migrations.AddField(
            model_name="candidaterecord",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidates",
                to="gallery.candidateclientcredential",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidaterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_candidate_id", ""), _negated=True),
                fields=("owner", "client_candidate_id"),
                name="gallery_unique_client_candidate_id",
            ),
        ),
        migrations.AddField(
            model_name="candidateuploadreceipt",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="upload_receipts",
                to="gallery.candidaterecord",
            ),
        ),
        migrations.AddField(
            model_name="candidateuploadreceipt",
            name="candidate_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="upload_receipts",
                to="gallery.candidateimage",
            ),
        ),
        migrations.AddField(
            model_name="candidateuploadreceipt",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="upload_receipts",
                to="gallery.candidateclientcredential",
            ),
        ),
        migrations.AddField(
            model_name="reviewworkitem",
            name="allowed_targets",
            field=models.ManyToManyField(
                blank=True,
                related_name="authorized_review_work_items",
                to="gallery.figureprototype",
            ),
        ),
        migrations.AddField(
            model_name="reviewworkitem",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_work_items",
                to="gallery.candidaterecord",
            ),
        ),
        migrations.AddField(
            model_name="reviewworkitem",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="figure_gallery_review_work_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateuploadreceipt",
            constraint=models.UniqueConstraint(
                fields=("owner", "idempotency_key"),
                name="gallery_unique_client_upload_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewworkitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("candidate",),
                name="gallery_one_open_review_per_candidate",
            ),
        ),
    ]
